spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurante?useSSL=false
    username: root
    password: root   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  jackson:
    time-zone: America/Sao_Paulo
    locale: es_ES
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    '[org.hibernate.sql]': debug
server:
  port: 8081
jwt:
  secret: secret
  expiration: 36000
